### PR TITLE
Route refactoring

### PR DESCRIPTION
**Pull request by jlvivero**
this fixes issue #11

### CODE REVIEW

**Comment by jlvivero** [comment]
Don't MERGE yet, review code and tell me what you think about it (if there's any mistake please let me know)

**Comment by A-deLuna** [comment]
In settings.js you're creating a new router and attaching methods to it, so that should be the object you're exporting. 
Also you shouldn't repeat the name of the route inside the router so you should delete '/settings' from line 8 and 27, please see the last example from the [routing docs](http://expressjs.com/guide/routing.html). 
Also please remove the last two empty lines from the file.

For mongoose here's an [example](http://mongoosejs.com/docs/documents.html) on how to update an object.

**Comment by A-deLuna** [comment]
It's getting there, though you're creating and exporting the object settingsRouter but you're attaching get and post methods to router that isn't definied in the file, does it run? 

Also please fix the indentation to 2 spaces and delete the space character at the end of line 45
@jlvivero

**Comment by A-deLuna** [comment]
line 25 throws an error, can't declare the object and a property that way, you should first declare the object information and then attatch that property

**Comment by A-deLuna** [comment]
thanks @jlvivero

**Pull request merged**
