### PR TITLE
added the likes and dislikes on the dashboard

### LINKED ISSUE #36: Likes should be shown in dashboard
in src/Tutors.js
pass new params to each TutorPanel in line 37
each tutor has all the data from models/User.js

in src/TutorPanel.js
display this params where 42 and 12 are hard coded

### PR DESCRIPTION
**Pull request by jlvivero**
fixes #36

### CODE REVIEW

**Comment by A-deLuna** [comment]
hmm este pr me esta tirando errores

**Comment by A-deLuna** [comment]
TypeError: this.props.likes is undefined

**Comment by jlvivero** [comment]
what, I tested it and it worked fine, it still works fine in the current version

**Comment by A-deLuna** [comment]
ya se que puede ser

**Pull request merged**
